### ISSUE TITLE
Telegraf2Hassio quits - ValueError: Publish topic cannot contain wildcards.

### ISSUE THREAD

**Issue by justinbyoung** [joaofl/hassio-addons#35]
Telegraf2Hassio dies after a couple of minutes with a ValueError: Publish topic cannot contain wildcards error. Not sure how to troubleshhot this. I am not seeing any odd characters in MQTT explorer, but I am assuming Telegraf2Hassio is failing before publishing any mqtt data.

Here is the config

```
mqtt_broker: localhost
mqtt_port: 1883
mqtt_user: username
mqtt_pass: password
telegraf_topic: telegraf/#
calc_rate: ""
log_level: debug
```

Here is the log output, Debug logging is enabled.

```
[15:17:12] INFO: Starting Telegraf2Hassio
[15:17:12] INFO Setup finished
[15:17:12] INFO Connected to MQTT Broker!
[15:18:12] INFO Added measurement UID: proxmox03_hddtemp_sda_aa_temperature
[15:18:12] INFO Added sensor: telegraf2ha/proxmox03/hddtemp_sda_aa/[temperature]
[15:18:12] INFO Added measurement UID: proxmox03_hddtemp_sdb_aa_temperature
[15:18:12] INFO Added sensor: telegraf2ha/proxmox03/hddtemp_sdb_aa/[temperature]
[15:18:12] INFO Added measurement UID: proxmox03_sensors_temp1_ca_temp_input
[15:18:12] INFO Added sensor: telegraf2ha/proxmox03/sensors_temp1_ca/[temp_input]
[15:18:12] INFO Added measurement UID: proxmox03_sensors_temp2_ca_temp_input
[15:18:12] INFO Added sensor: telegraf2ha/proxmox03/sensors_temp2_ca/[temp_input]
[15:18:12] INFO Added measurement UID: proxmox03_sensors_temp3_ca_temp_input
[15:18:12] INFO Added sensor: telegraf2ha/proxmox03/sensors_temp3_ca/[temp_input]
[15:18:12] INFO Added measurement UID: proxmox03_sensors_temp4_ca_temp_input
[15:18:12] INFO Added sensor: telegraf2ha/proxmox03/sensors_temp4_ca/[temp_input]
[15:18:12] INFO Added measurement UID: proxmox03_sensors_temp5_ca_temp_input
[15:18:12] INFO Added sensor: telegraf2ha/proxmox03/sensors_temp5_ca/[temp_input]
[15:18:12] INFO Added measurement UID: proxmox03_sensors_temp6_ca_temp_input
[15:18:12] INFO Added sensor: telegraf2ha/proxmox03/sensors_temp6_ca/[temp_input]
[15:18:12] INFO Added measurement UID: proxmox03_sensors_vcore_ae_in_alarm
[15:18:12] INFO Added measurement UID: proxmox03_sensors_vcore_ae_in_beep
[15:18:12] INFO Added measurement UID: proxmox03_sensors_vcore_ae_in_input
[15:18:12] INFO Added measurement UID: proxmox03_sensors_vcore_ae_in_max
[15:18:12] INFO Added measurement UID: proxmox03_sensors_vcore_ae_in_min
[15:18:12] INFO Added sensor: telegraf2ha/proxmox03/sensors_vcore_ae/[in_alarm,in_beep,in_input,in_max,in_min]
Traceback (most recent call last):
  File "/opt/telegraf2hassio/telegraf2hassio.py", line 62, in <module>
    client.loop_forever()
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/opt/telegraf2hassio/telegraf2hassio.py", line 11, in data_received
    tp.send(data)
  File "/opt/telegraf2hassio/parser.py", line 125, in send
    is_new = self.announce_new(host_name, sensor_name, jdata)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/telegraf2hassio/parser.py", line 108, in announce_new
    _, is_new_m = current_sensor.add_measurement(measurement_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/telegraf2hassio/parser.py", line 190, in add_measurement
    current_measurement = measurement(self, measurement_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/telegraf2hassio/parser.py", line 216, in __init__
    self.parent_sensor.parent_host.parent_listener.transmit_callback(f"{self.topic}/config", json.dumps(config_payload), retain=True)
  File "/opt/telegraf2hassio/telegraf2hassio.py", line 15, in data_transmit
    client.publish(topic, payload, retain=retain)
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 1233, in publish
    raise ValueError('Publish topic cannot contain wildcards.')
ValueError: Publish topic cannot contain wildcards.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by joaofl** [comment]
I have just pushed a potential fix for that. Please give it a try and let me know.

**Comment by justinbyoung** [comment]
Hi @joaofl testing now. So far so good, it looks to be working as expected. Thanks for the fix.

**Comment by joaofl** [comment]
So I will close this issue. If the problem comes up again I can re-open it.
